### ISSUE TITLE
macOS Screen Recording Permission Not Recognized

### ISSUE THREAD

**Issue by iDataist** [pickle-com/glass#38]
# Environment
- **OS**: macOS Sequoia 15.5 (Darwin 24.5.0)
- **Glass Version**: 0.1.1 
- **Installation Type**: Both development (`npm start`) and downloaded Mac desktop app
- **Electron Version**: 30.5.1
- **Bundle ID**: `com.deeplink.pickleglass`

# Two Distinct Issues Identified

## Issue 1: Local Development Build - Permission Detection Failure
- ✅ Granted screen recording permission to "Electron" in System Settings
- ❌ **App still shows error**: "Please grant screen recording access in System Preferences" 
- ❌ Cannot proceed past API key validation due to false permission failure
- **Root Cause**: Permission detection logic fails even when permission is properly granted

## Issue 2: Official Mac Desktop App - Listen Feature Failure  
- ✅ Downloaded official Glass Mac desktop application
- ✅ Granted screen recording permission - **no permission errors displayed**
- ✅ **Ask feature works**: Can ask questions about screen content successfully
- ✅ Screen capture functionality is working for Ask queries
- ❌ **Listen feature fails**: Clicking "Listen" produces no transcripts or audio capture
- ❌ Listen session appears active but generates no output

### Problem Description
The Glass application consistently reports that screen recording permission is not granted, even after explicitly granting permission to Electron (/Users/****/Downloads/glass/node_modules/electron/dist/)  in System Settings → Privacy & Security → Screen & System Audio Recording. 

### Steps to Reproduce
1. Clone the repo and run it with `npm start`
2. Grant screen recording permission to "Electron" in macOS System Settings
3. Enter API key in Glass window and click "Confirm"
4. Observe error message: "Please grant screen recording access in System Preferences"
5. Even when bypassing permission check, clicking "Listen" captures nothing

### Console Output
```
[Permissions] Screen capture test failed: Failed to get sources.
[Permissions] System permissions status: { microphone: true, screen: false, needsSetup: true }
```

### Technical Analysis
The permission check in `src/electron/windowManager.js` (lines 2190-2195) uses:
```javascript
const sources = await desktopCapturer.getSources({ 
    types: ['screen'], 
    thumbnailSize: { width: 1, height: 1 } 
});
permissions.screen = sources && sources.length > 0;
```

This test consistently fails with "Failed to get sources" despite macOS showing permission as granted.

### Root Cause Investigation
1. **macOS Sequoia Compatibility**: Potential changes in Sequoia 15.5 permission handling
2. **Bundle ID Mismatch**: The app identifies as `com.deeplink.pickleglass` but users add "Electron" to permissions
3. **Permission Cache**: macOS may cache permission states and not recognize changes without app restart

### Expected Behavior
- Screen recording permission should be properly detected after being granted
- App should either auto-request permission or clearly indicate which app to authorize

### Actual Behavior
- Permission check always returns `screen: false`
- App gets stuck in API key validation loop

### Suggested Solutions
1. **macOS Sequoia Compatibility**: Update Electron or permission handling for Sequoia 15.5
2. **Improve Permission Detection**: Add fallback methods to test screen recording capability
3. **Bundle ID Consistency**: Ensure permission requests use consistent app identity
4. **User Guidance**: Provide clearer instructions on which app to authorize in System Settings
5. **Auto-Request**: Implement automatic permission request dialog when needed
6. **Graceful Degradation**: Allow app to function with limited features if permissions unavailable

### Workarounds Attempted
- ✅ Manually adding Electron to Screen Recording permissions
- ✅ Restarting application after granting permission
- ❌ None successful - issue persists across all versions and approaches

### Additional Notes
- Microphone permission detection works correctly (`microphone: true`)
- Issue affects core functionality (Listen feature completely non-functional)
- **macOS Sequoia 15.5 specific**: May be related to stricter permission handling in latest macOS
- Similar issues may affect other Electron-based apps with screen recording needs on Sequoia

### Priority
**High** - Core functionality (Listen feature) is completely unusable on macOS Sequoia 15.5

**Comment by tarsyang** [comment]
Thanks for the reporting the issue we are working on this problem

**Comment by DarellBoyle** [comment]
Maybe try resetting TCC.db to force fresh permission grant?

**Comment by Rabneba** [comment]
Have the same problem on Sequoia 15.5 : ( 

TCC.db didn't help

**Comment by tarsyang** [comment]
This issue is fixed in our latest version. Thanks!

**Comment by padala** [comment]
Looks like the issue still persists on latest version as well. Thanks

**Comment by roshaans** [comment]
still persists
